#########################################
#           公共环境配置                 #
#########################################

# 指定配置环境
spring:
  profiles:
    active: dev
server:
  tomcat:
    uri-encoding: UTF-8
