server:
  port: 8901

spring:
  application:
    name: application-user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    uesrname: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot-application?autoReconnect=true&useSSL=false

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  instance:
    #\u6CE8\u518C\u670D\u52A1\u7684\u65F6\u5019\u4F7F\u7528\u670D\u52A1\u7684ip\u5730\u5740
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/
