#########################################
#           开发环境配置                 #
#########################################


server:
  port: 8901

spring:
  application:
    name: application-user-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    uesrname: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot-application?autoReconnect=true&useSSL=false

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  instance:
    #优先使用ip地址进行服务注册,而非主机名
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:@project.version@
  client:
    serviceUrl:
      defaultZone: http://api:eureka@localhost:8900/eureka/